### ISSUE TITLE
Font size ignored

### ISSUE THREAD

**Issue by fmatosic** [SimonFairbairn/SwiftyMarkdown#108]
Changing the font size makes no difference. 
Also if I do this for all style but the issue exists:
[setFontSizeForAllStyles gets ignored](https://github.com/SimonFairbairn/SwiftyMarkdown/issues/88)
Using SwiftyMarkdown 1.2.3  and tried 1.2
` let swiftytext = SwiftyMarkdown(string: mdString)
                    swiftytext.body.color = UIColor.darkGray
                    swiftytext.h2.fontStyle = .bold
                    swiftytext.body.fontSize = 50`

**Comment by fmatosic** [comment]
If I set a fontName (one that exists on the system) it will change font size eg. 
`swiftytext.body.fontName = "Courier"`
How do I set the System font Name?

**Comment by fmatosic** [comment]
let sFontName = UIFont.systemFont(ofSize: 12).familyName
And then set the font name

**Comment by takehilo** [comment]
I got the same issue. Thanks for your solution!

**Comment by MahmoudZinji** [comment]
I am facing the same issue 
How can i resolve this if i am using NON system font ?
