### ISSUE TITLE
support with swiftui

### ISSUE THREAD

**Issue by reinaldoriant** [SimonFairbairn/SwiftyMarkdown#122]
hello, can this support in swift UI, and do you have a sample ?

**Comment by rastislv** [comment]
You can use any implementation of _UIViewRepresentable_. Here is some simple one

```
struct UIKTextView: UIViewRepresentable {
    @Binding var text: NSAttributedString

    func makeUIView(context: Context) -> UITextView {
        UITextView()
    }

    func updateUIView(_ uiView: UITextView, context: Context) {
        uiView.attributedText = text
    }
}
```

And then

`UIKTextView(text: .constant(SwiftyMarkdown(string: "some **bold** markdown text").attributedString()))`
