### ISSUE TITLE
Support for inline images

### ISSUE THREAD

**Issue by SimonFairbairn** [SimonFairbairn/SwiftyMarkdown#2]
Using `NSTextAttachment`:

```
let img = UIImage(named:"image")
let textAttachment = NSTextAttachment(data: nil, ofType: nil)
textAttachment.image = img
let imageString = NSAttributedString(attachment: textAttachment)
```

**Comment by fusionbeam** [comment]
Is this supported now?

**Comment by daviddelmonte** [comment]
Hi, I have the same question. I saw your comment on using `NSTextAttachment`, but I have many images in my .md pages. If you only support `NSTextAttachment`, could you please provide an example of how to integrate this with an .md file. Many thanks.

**Comment by SimonFairbairn** [comment]
Unfortunately I still haven't gotten around to this one yet. Sorry about that!

**Comment by brunomunizaf** [comment]
2019 and we still need this.

**Comment by dhruveonmars** [comment]
Hey @SimonFairbairn, I was wondering if there has been any update on this?
