### ISSUE TITLE
Swift 3 Support - I think I'm getting close

### ISSUE THREAD

**Issue by wm-j-ray** [SimonFairbairn/SwiftyMarkdown#22]
I'm still left with an error on line 297

    let newRange  = hasRange.lowerBound...hasRange.upperBound
    foundCharacters = foundCharacters + matchedCharacters.substring(with: newRange)

I get 'Cannot convert value of type 'ClosedRange<index>' to expected argument type 'Range<index>' and I have tried to figure it out with no luck.

Any help greatly appreciated.

**Comment by SimonFairbairn** [comment]
There is now a Swift 3 Branch that should be fully compatible with latest version of Swift.
