### ISSUE TITLE
New line at the end of attributed string

### ISSUE THREAD

**Issue by jakunico** [SimonFairbairn/SwiftyMarkdown#23]
We're getting a new line character at the end of the generated string as seen here:

``` swift
let attributedString = SwiftyMarkdown(string: "Please **work**").attributedString()
print(attributedString.string) //prints: ""Please work\n"
```

Commenting the following line does seem to fix this case:

``` swift
// Append a new line character to the end of the processed line
attributedString.appendAttributedString(NSAttributedString(string: "\n"))
```

though that's probably there for a reason :D

**Comment by BradleyDeLar** [comment]
Did you make any headway with this?

**Comment by neoneye** [comment]
There is still a newline at the end of the string. Perhaps add a flag wether or not to add the newline.
