### ISSUE TITLE
Support for Links inside bold

### ISSUE THREAD

**Issue by ivanbruel** [SimonFairbairn/SwiftyMarkdown#25]
I was using this library to work on Reddit's markdown for [Reddit-MVVM-Benchmark](http://github.com/ivanbruel/Reddit-MVVM-Benchmark) and I hit a wall when it comes to tags inside tags, especially this use case:

`**Al Kindle, captain of [Team Half Fast Astronaut](https://www.facebook.com/Teamhfa):**`

Is this a library limitation or rather a bug on how the parsing is working?

**Comment by SimonFairbairn** [comment]
It's a current limitation of the library but shouldn't be too tricky to overcome.

**Comment by MarvinNazari** [comment]
Any workaround for this issue?

**Comment by CodingSam** [comment]
Any update on this?

**Comment by rajdev** [comment]
work around:
**Al Kindle, captain of **[Team Half Fast Astronaut](https://www.facebook.com/Teamhfa):
