### ISSUE TITLE
fatalError() on failable initializer??

### ISSUE THREAD

**Issue by ishaanSejwal** [SimonFairbairn/SwiftyMarkdown#36]
@SimonFairbairn Why does line 121 in SwiftMarkdown.swift have`fatalError("Couldn't read string")` ? If it is a failable initializer, I dont know why you have mentioned `fatalError("Couldn't read string")`? `return nil` should suffice.

Please clear this for me. Thanks.

**Comment by SimonFairbairn** [comment]
Yep, you're right. Left over from the early days.
