### ISSUE TITLE
Support for different font sizes

### ISSUE THREAD

**Issue by jodyscho** [SimonFairbairn/SwiftyMarkdown#42]
Would like to be able to specify a font size in the BasicStyle. Currrently I use a custom font and have a table that determines the font size based on category size but SwiftyMarkdown gets font sizes from the OS. Some of our custom fonts are a little to small when displayed with system font sizes for the categories.

Hope this makes sense. BTW, great job on SwiftyMarkdown!

**Comment by lucasromanomr** [comment]
https://github.com/SimonFairbairn/SwiftyMarkdown/pull/43

**Comment by SimonFairbairn** [comment]
0.3.5 is now available, which has all of @lucasromanomr's work in there.
