### ISSUE TITLE
"Fatal error: String index is out of bounds" for particular string

### ISSUE THREAD

**Issue by christoph-verse** [SimonFairbairn/SwiftyMarkdown#61]
A string index out of bounds fatal error is produced when converting this text into an attributed string:

```
let text = "[**\\!bang**](https://duckduckgo.com/bang) "
let md = SwiftyMarkdown(string: text)
let string = md.attributedString()
```

<img width="941" alt="Screen Shot 2019-04-16 at 10 00 39 AM" src="https://user-images.githubusercontent.com/45858669/56229336-8d7c3380-602e-11e9-88af-60990d9c08d2.png">

**Comment by christoph-verse** [comment]
Found this workaround to prevent the crash, but the output isn't quite right:

`if matchedCharacters.count > 1 && hasRange.upperBound < matchedCharacters.endIndex {`

**Comment by jonchui** [comment]
We're seeing a similar issue in our app when converting a string into attributed string - @christoph-verse did you find a workaround that still got you the right output?

**Comment by christoph-verse** [comment]
@jonchui I did, I just changed the line to the above and it worked.  To be honest though, I'm going moving to using [Down](https://github.com/iwasrobbed/Down) which is maintained by a friend of mine.
