### ISSUE TITLE
Weird link parsing

### ISSUE THREAD

**Issue by heumn** [SimonFairbairn/SwiftyMarkdown#67]
```
let markdownString = "[Link1](http://voyagetravelapps.com/) test, testing another link [Link2](http://voyagetravelapps.com/)"
let parser = SwiftyMarkdown(string: markdownString)
textLabel.attributedText = parser.attributedString()
```

Why would this produce a continuous blue text (link)?

![Skjermbilde 2020-01-12 kl  11 31 05](https://user-images.githubusercontent.com/1769314/72217511-378ddb00-352f-11ea-8803-a98a4222300e.png)

Github for comparison:

"[Link1](http://voyagetravelapps.com/) test, testing another link [Link2](http://voyagetravelapps.com/)"

**Comment by SimonFairbairn** [comment]
This is a bug with the attributed string not clearing out the link attributes between the two links. Updating to 1.0.1 should fix it.

**Comment by heumn** [comment]
Awesome! Tested multiple markdown projects and fell in love with this one. Was so bummed out when the link parser was broken. Glad you fixed it @SimonFairbairn!
