### ISSUE TITLE
Links not appearing correctly 

### ISSUE THREAD

**Issue by johnswifttt** [SimonFairbairn/SwiftyMarkdown#69]
### Issue

When adding an image and a bold title to the same line, links do not appear properly. 

Example string in markdown file:
```
![Image](play) **Bold Title** This is a test. The link will not show up here because there is an image and bold text on same line. The link is here: [Links](https://espn.com/)
```

This is how the string above appears. Notice the link turned into weird characters:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/10701375/73372927-f8c58800-4285-11ea-9f9b-46799c979370.png">

### How to reproduce
Use the string above in a markdown file and display it in the app.

### Device
- iPhone 8 Plus 13.2 (Simulator)

**Comment by SimonFairbairn** [comment]
Thanks for the detailed bug reports. I'll look into all of these and get a fix out as soon as possible.

**Comment by johnswifttt** [comment]
No problem! Thanks for quickly fixing things!
