### ISSUE TITLE
Cannot set link.color 

### ISSUE THREAD

**Issue by pbridi** [SimonFairbairn/SwiftyMarkdown#7]
Using _link.color_ doesn't seem to change the color for links. _link.fontName_ works fine

`let md = SwiftyMarkdown(string: "![Screenshot](http://f.cl.ly/items/12332k3f2s0s0C281h2u/swiftymarkdown.png)")`
`md.link.color = UIColor.greenColor()`
`md.link.fontName = "ArvilSans"`
`textAreaView.attributedText = md.attributedString()`

Any ideas why?

**Comment by SimonFairbairn** [comment]
UITextView has its own styles for links that I think can override the NSAttributedString styles. 

I'll take a look, but in the meantime you can use the `linkTextAttributes` of UITextView or you can set the `tintColor` as links also inherit from this.

**Comment by SimonFairbairn** [comment]
For example:

    textAreaView.linkTextAttributes = [NSForegroundColorAttributeName : UIColor.greenColor()]

**Comment by pbridi** [comment]
Thanks Simon, using linkTextAttributes works perfectly! Sorry for that.

**Comment by Vortec4800** [comment]
I'm running into the same issue, but with a UILabel, which doesn't seem to have a linkTextAttributes property. How might I set this for a label instead of a text view?
