### ISSUE TITLE
Question: Styling bullets

### ISSUE THREAD

**Issue by johnswifttt** [SimonFairbairn/SwiftyMarkdown#70]
### Question

I want to style the bullet points. 
1. Can I change the size of this bullet? I want it to be a larger dot
2. Can I make this entire paragraph indent so that it does not wrap underneath the bullet? Right not in the picture below, you'll see that the text on the second and third lines do not indent with the bullet

Example:
<img width="368" alt="Screen Shot 2020-01-29 at 11 21 05 AM" src="https://user-images.githubusercontent.com/10701375/73375233-7b9c1200-4289-11ea-875a-edbce80551d8.png">

**Comment by SimonFairbairn** [comment]
SwiftyMarkdown 1.0.2 adds a `bullet` property that will allow you to choose whatever character(s) you want for the bullet style. It also correctly indents bulleted lists (and blockquotes, which had the same issue).

**Comment by johnswifttt** [comment]
Thank you!
