### ISSUE TITLE
Indented list color incorrect

### ISSUE THREAD

**Issue by johnswifttt** [SimonFairbairn/SwiftyMarkdown#72]
### Issue

The colors for indented lists are incorrect (unless I am setting the colors incorrectly). We support light and dark mode users can switch between them. Notice in the picture below, that in dark mode, the indented lists don't change colors. 

This is what I set in code:
```swift
markdown.body.color = .red
```

<img width="197" alt="Screen Shot 2020-01-30 at 3 58 21 PM" src="https://user-images.githubusercontent.com/10701375/73489863-5ab2ea00-4379-11ea-99b1-7e4fa2b893aa.png">
<img width="261" alt="Screen Shot 2020-01-30 at 3 58 14 PM" src="https://user-images.githubusercontent.com/10701375/73489868-5c7cad80-4379-11ea-8468-8b83681731a0.png">

**Comment by SimonFairbairn** [comment]
The current version doesn't support indented lists just yet but the next version will!

**Comment by julo15** [comment]
@SimonFairbairn do you know about how much work it would be to add that support?

i'm actually not seeing bullets being indented at all. (i'm using an unordered list, though.) trying to figure out what my options are at the moment.

**Comment by julo15** [comment]
ah interesting.. if you replace _space-space-asterisk_ with _tab-asterisk_, it actually shows up reasonably in swifty markdown
