### ISSUE TITLE
Phone URL not working and crashing the app after long press

### ISSUE THREAD

**Issue by kacper1703** [SimonFairbairn/SwiftyMarkdown#80]
Xcode 11.3, iOS 13.3, SDK 1.1.0

Repro steps:
- Create a UITextView on a storyboard
```swift
textView.isSelectable = true
textView.isEditable = false
textView.delegate = self
textView.dataDetectorTypes = [.phoneNumber]
let text = """
Call us at [0 123 456](tel://0 123 456). We'll answer your call. Or go to [our website](https://www.google.com).
"""
let markdown = SwiftyMarkdown(string: text)
textView.attributedString = markdown.attributedString() 
```

Result:
- Tapping the phone number doesn't call `textView(_ textView: UITextView, shouldInteractWith URL: URL, in characterRange: NSRange, interaction: UITextItemInteraction)`
- Long pressing the phone number causes the app to crash with an ambiguous stack trace.

**Comment by SimonFairbairn** [comment]
Thanks for the detailed bug report! Will look into this for the next version.

**Comment by kacper1703** [comment]
I found the issue - it's actually because system cannot create an NSURL with whitespace in it. Removing whitespace from the link (`tel://0123456`) made it work.

**Comment by SimonFairbairn** [comment]
Thanks for letting me know!
