### ISSUE TITLE
Getting markdown back

### ISSUE THREAD

**Issue by SolorzanoJose** [SimonFairbairn/SwiftyMarkdown#90]
Is there a way to get markdown back after having the nsattributedstring? Let's say I want to use this in an editable uitextview, how can I transform back into markdown?

**Comment by SimonFairbairn** [comment]
I assume your use case would be something like the user is editing text and applying rich text formatting visually and you want to create a new Markdown string from that rich text, so the user never actually enters any Markdown syntax themselves?

In that case, the answer is no. Unfortunately this library only converts plain text Markdown to an NSAttributedString. It’s not currently possible with SwiftyMarkdown to go the other way and to be honest it’s not really something I’d be interested in adding.

If you wanted to take a crack at it though, I’d be happy to accept a PR.
